services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  pgdata: